<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="BuildVersion.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ReferenceDirectory Condition="'$(ReferenceDirectory)' == ''">$(MSBuildThisFileDirectory)lib</ReferenceDirectory>
    <AssemblyName>MiniRealisticAirways</AssemblyName>
    <Description>MiniRealisticAirwaysMod</Description>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12.0</LangVersion>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=/_/MiniRealisticAirways</PathMap>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.4" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ReferenceDirectory)/Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>$(ReferenceDirectory)/DOTween.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ReferenceDirectory)/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ReferenceDirectory)/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ReferenceDirectory)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(ReferenceDirectory)/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Localization">
      <HintPath>$(ReferenceDirectory)/Unity.Localization.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(ReferenceDirectory)/UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(ReferenceDirectory)/UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(ReferenceDirectory)/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(ReferenceDirectory)/UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(ReferenceDirectory)/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(ReferenceDirectory)/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>$(ReferenceDirectory)/UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Import Project="BuildMetadata.targets" />
</Project>
